export default {
  machines: [
    "Brodeuse numérique",
    "Découpeuse laser",
    "Découpeuse vinyle",
    "Fraiseuse numérique",
    "Imprimante 3D",
    "Imprimante résine",
    "Imprimante laser noir et blanc",
    "Imprimante laser couleur",
    "Arduino",
    "micro:bit",
    "Makey Makey",
    "Machine à coudre",
    "Raspberry Pi",
    "Capteurs",
    "Actuateurs",
    "Fer à souder",
    "Outils à bois",
    "Perçeuse",
    "Ponçeuse",
    "Scie",
    "Scie à chantourner",
  ],
  materials: [
    "Vinyle",
    "Flex",
    "Silicone",
    "Bois CP 3mm",
    "Bois CP 5mm",
    "Palettes",
    "Plexi/PMMA",
    "Carton",
    "Papier",
    "Caoutchouc Tampon",
    "Tissu",
    "Cuir",
    "Résine",
    "Filament PLA",
    "Filament PETG",
    "Filament NYLON",
    "Filament ABS",
    "Fil électrique",
    "câbles Dupont",
    "câble USB",
    "Piles LR3",
    "Piles LR6",
    "Batterie Lithium 3,6V",
    "Batterie 9V",
  ],
};
